### PR TITLE
Implemented Last reading time (Local Time Zone) in Dashboard

### PR DESCRIPTION
**Pull request by adukale**
Dashboard will show last reading's time in Chart header.
image

### CODE REVIEW

**Comment by adukale** [comment]
Have implemeted this in mobile app also, but haven't pushed that code because I am yet to work on styling for the same.
@Savjee Let me know if you have any suggestions.
image

**Comment by Savjee** [comment]
Thanks for the PR!
Could you maybe cleanup the date a little bit? Showing timezone data seems a bit too much, no?

**Comment by adukale** [comment]
@Savjee Done.  Below is the new format:
image

**Comment by Savjee** [comment]
Much better! Thank you!

**Pull request merged**
